from astropy import units as u, constants as const
import numpy as np

Particles = {

    "e-": {
        "name": "electron",
        "mass": const.m_e,
        "charge": -1,
        "spin": 1/2,
        "half-life": np.inf * u.s,
        "antimatter": False,
        "generation": 1,
        "class": "lepton",
        "lepton number": 1,
        "baryon number": 0,
    },

    "e+": {
        "name": "positron",
        "mass": const.m_e,
        "charge": 1,
        "spin": 1/2,
        "half-life": np.inf * u.s,
        "antimatter": True,
        "generation": 1,
        "class": "antilepton",
        "lepton number": -1,
        "baryon number": 0,
    },

    "mu-": {
        "name": "muon",
        "mass": 1.883_531_594e-28 * u.kg,
        "charge": -1,
        "spin": 1/2,
        "half-life": 2.1969811e-6 * u.s,
        "antimatter": False,
        "generation": 2,
        "class": "lepton",
        "lepton number": 1,
        "baryon number": 0,
    },

    "mu+": {
        "name": "antimuon",
        "mass": 1.883_531_594e-28 * u.kg,
        "charge": 1,
        "spin": 1/2,
        "half-life": 2.1969811e-6 * u.s,
        "antimatter": True,
        "generation": 2,
        "class": "antilepton",
        "lepton number": -1,
        "baryon number": 0,
    },

    "tau-": {
        "name": "tau",
        "mass": 3.167_47e-27 * u.kg,
        "charge": -1,
        "spin": 1/2,
        "half-life": 2.906e-13 * u.s,
        "antimatter": False,
        "generation": 3,
        "class": "lepton",
        "lepton number": 1,
        "baryon number": 0,
    },

    "tau+": {
        "name": "antitau",
        "mass": 3.167_47e-27 * u.kg,
        "charge": 1,
        "spin": 1/2,
        "half-life": 2.906e-13 * u.s,
        "antimatter": True,
        "generation": 3,
        "class": "antilepton",
        "lepton number": -1,
        "baryon number": 0,
    },

    "nu_e": {
        "name": "electron neutrino",
        "charge": 0,
        "spin": 1/2,
        "half-life": np.inf * u.s,
        "antimatter": False,
        "generation": 1,
        "class": "lepton",
        "lepton number": 1,
        "baryon number": 0,
    },

    "anti_nu_e": {
        "name": "electron antineutrino",
        "charge": 0,
        "spin": 1/2,
        "half-life": np.inf * u.s,
        "antimatter": True,
        "generation": 1,
        "class": "antilepton",
        "lepton number": -1,
        "baryon number": 0,
    },

    "nu_mu": {
        "name": "muon neutrino",
        "charge": 0,
        "spin": 1/2,
        "half-life": np.inf * u.s,
        "antimatter": False,
        "generation": 2,
        "class": "lepton",
        "lepton number": 1,
        "baryon number": 0,
    },

    "anti_nu_mu": {
        "name": "muon antineutrino",
        "charge": 0,
        "spin": 1/2,
        "half-life": np.inf * u.s,
        "antimatter": True,
        "generation": 2,
        "class": "antilepton",
        "lepton number": -1,
        "baryon number": 0,
    },

    "nu_tau": {
        "name": "tau neutrino",
        "charge": 0,
        "spin": 1/2,
        "half-life": np.inf * u.s,
        "antimatter": False,
        "generation": 3,
        "class": "lepton",
        "lepton number": 1,
        "baryon number": 0,
    },

    "anti_nu_tau": {
        "name": "tau antineutrino",
        "charge": 0,
        "spin": 1/2,
        "half-life": np.inf * u.s,
        "antimatter": True,
        "generation": 3,
        "class": "antilepton",
        "lepton number": -1,
        "baryon number": 0,
    },

    "p": {
        "name": "proton",
        "mass": const.m_p,
        "charge": 1,
        "spin": 1/2,
        "half-life": np.inf * u.s,
        "class": "baryon",
        "lepton number": 0,
        "baryon number": 1,
    },

    "p-": {
        "name": "antiproton",
        "mass": const.m_p,
        "charge": -1,
        "spin": 1/2,
        "half-life": np.inf * u.s,
        "class": "antibaryon",
        "lepton number": 0,
        "baryon number": -1,
    },

    "n": {
        "name": "neutron",
        "mass": const.m_n,
        "charge": 0,
        "spin": 1,
        "half-life": 881.5 * u.s,
        "class": "baryon",
        "lepton number": 0,
        "baryon number": 1,
    },

    "antineutron": {
        "name": "antineutron",
        "mass": const.m_n,
        "charge": 0,
        "spin": 1,
        "half-life": 881.5 * u.s,
        "class": "antibaryon",
        "lepton number": 0,
        "baryon number": -1,
    },

}