# zizmor finds potential security vulnerabilities in GitHub workflow
# files. Documentation: https://woodruffw.github.io/zizmor

rules:
  unpinned-uses:
    config:
      policies:
        actions/*: ref-pin
        astral-sh/setup-uv: ref-pin
        codecov/codecov-action: ref-pin
        conda-incubator/setup-miniconda: ref-pin
        pypa/*: ref-pin
        scientific-python/*: ref-pin
        ts-graphviz/setup-graphviz: ref-pin

# Put settings that we intend to fix later on below this line. If we
# decide that a potential security vulnerability does not necessitate a
# fix, append a comment like `# zizmor: ignore[unpinned-uses]` to the
# line or set the appropriate configuration options above.

  excessive-permissions:
    ignore:
    - create-release-issue.yml:11:3
    - changelog.yml:9:3
    - changelog.yml:10:3
    - comment-on-pr.yml:8:3
    - mint-release.yml:17:3
    - unlabel-pr-after-merge.yml:8:3
    - update-pinned-reqs.yml:9:3
  template-injection:
    ignore:
    - create-release-issue.yml:21:7
    - mint-release.yml:41:7
    - mint-release.yml:47:7
    - mint-release.yml:53:7
    - mint-release.yml:61:7
    - mint-release.yml:66:7
  use-trusted-publishing:
    ignore:
    - publish-to-pypi.yml:36:7
