# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

formats:
- htmlzip

build:
  os: ubuntu-22.04
  tools:
    # Use most recent version supported by Numba
    python: '3.10'
  apt-packages:
  - graphviz
  jobs:
    pre_create_environment:
    - python -m pip install --upgrade setuptools pip

sphinx:
  fail_on_warning: true

python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs
  system_packages: true
