# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

formats:
- htmlzip

build:
  os: ubuntu-20.04
  tools:
    python: '3.10'
  jobs:
    pre_install:
    - python -m pip install --upgrade setuptools pip


# Optionally set the version of Python and requirements required to build your docs
python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs
  system_packages: true
