# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

sphinx:
  configuration: docs/conf.py

formats:
- htmlzip

build:
  os: ubuntu-24.04
  tools:
    python: '3.14'

  apt_packages:
  - graphviz

  jobs:

    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest

    create_environment:
      - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"

    post_create_environment:
      - uv tool install nox --with=nox-uv

    install:
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --group docs

    build:
      html:
      - nox -s docs

      htmlzip:
        - nox -s docs_bundle_htmlzip

    post_build:
    - echo $'\n'⚠️ For help deciphering documentation build error messages, see:$'\n\n'\ \ https://docs.plasmapy.org/en/latest/contributing/doc_guide.html#troubleshooting
