# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

sphinx:
  configuration: docs/conf.py

formats:
- htmlzip

build:
  os: ubuntu-24.04
  tools:
    python: '3.14'

  apt_packages:
  - graphviz

  jobs:

    create_environment:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest

    install:
      - uv sync --exact --frozen --only-group nox --only-group docs --python 3.14

    build:
      html:
      - uvx nox -s docs

      htmlzip:
      - uvx nox -s docs_bundle_htmlzip

    post_build:
    - echo $'\n'⚠️ For help deciphering documentation build error messages, see:$'\n\n'\ \ https://docs.plasmapy.org/en/latest/contributing/doc_guide.html#troubleshooting
