name: conda-forge

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of PlasmaPy to install from conda-forge
        required: true
        default: 2025.10.0

permissions: {}

jobs:

  conda-forge:

    name: Install PlasmaPy ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    defaults:
      run:
        shell: bash -el {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12', '3.13', '3.14']

    steps:
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python_version }}
        channels: conda-forge

    - name: Install PlasmaPy from conda-forge
      run: conda install --yes plasmapy=${GITHUB_EVENT_INPUTS_VERSION}
      env:
        GITHUB_EVENT_INPUTS_VERSION: ${{ github.event.inputs.version }}

    - name: Import PlasmaPy and print version
      run: python -c "import plasmapy; print(plasmapy.__version__)"
