name: Label PR

# The labels to be added are defined in .github/labeler.yml

on:
- pull_request_target

jobs:
  labeler:
    name: Add labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v5
